### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by tchaler2017** [mk-fg/trilobite#1]
Hello, i am getting errors when i am trying to run:
 $python trilobite.py
root@kali:~/trilobite# python trilobite.py 
Traceback (most recent call last):
  File "trilobite.py", line 446, in <module>
    old_sets, old_essence = pull_sets()
  File "trilobite.py", line 434, in pull_sets
    ipset = Popen([cfg['fs']['bin']['ipset'], 'save'], stdout=PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Did i miss something?? Thanks

**Comment by mk-fg** [comment]
Hi,

> ipset = Popen([cfg['fs']['bin']['ipset'], 'save'], stdout=PIPE)
> OSError: [Errno 2] No such file or directory

Since there's "sets" section defined in the config file, i.e. something like this:
https://github.com/mk-fg/trilobite/blob/42ad3c0/trilobite.yaml.example#L32-L46

...script tries to run ipset command, using path specified in "fs" section, e.g.:
https://github.com/mk-fg/trilobite/blob/42ad3c0/trilobite.yaml.example#L24

...and apparently there's no such file/binary - you either need to install "ipset" tool or don't use (remove) "sets" section in the config, depending on whether you need to init these.

**Comment by mk-fg** [comment]
> you either need to install "ipset" tool or don't use (remove) "sets" section in the config

...or, alternatively, just specify correct path to it :)

Paths in linked example config are quite outdated - (some/most?) modern linuxes only use /usr/bin, with no special sbin or /bin or whatever.
Though didn't see one that didn't at least keep sbin symlink, so it's more likely to be missing binary, not path.
